Шаблонизируй это
htmlacademy-ecmascript/1763091-cinemaddict-15 pull request #4
Opened 2021-08-16 20:18 UTC by DPGrachev

сделал функцию, генерирующую временные данные (моки), на основе которых теперь заполняются компоненты верстки.

2021-08-16 20:21 UTC, DPGrachev commented
Данные генерируются, компоненты по ним отрисовываются. Вроде по заданию все сделал. В обучении было сказано про рефакторинг кода, но пока мне тяжело дается понять, где и что можно сократить, как написать почище. Буду благодарен за обратную связь в этом вопросе)  Ну и конечно если что-то упустил - жду замечаний) Спасибо!)

2021-08-16 20:26 UTC, DPGrachev commented
И дату по dayjs я везде указал просто сегодняшнюю, везде привел ее просто к формату по образцу. Если принципиально нужно создать генерацию разных дат через dayjs, то сделаю. Просто как я понял главное к нужному формату приводить дату, которая будет потом приходить с сервера, поэтому не стал углубляться в документацию dayjs

2021-08-17 05:31 UTC, what1s1ove requested changes
В целом задание сделано, но давай мы с тобой попытаемся убрать как можно больше `for`'ов, и заменим их на методы массивов

2021-08-17 05:31 UTC, what1s1ove commented on src/mock/film-card-mock.js
> +const MOVIE_TITLES = ['begin', 'ironman', 'world', 'hulk', 'spiderman', 'batman', 'superman', 'aquaman', 'cars', 'water', 'love store', 'world of war', 'warcraft', 'sherlock'];
константы идут перед основным кодом

2021-08-17 05:31 UTC, what1s1ove commented on src/mock/film-card-mock.js
> +    while(arr.indexOf(value) >= 0){
вот тут вот сложно, но с другой стороны, оно работает, и мы скоро это уберем 🙂

2021-08-17 05:31 UTC, what1s1ove commented on src/view/film-popup.js
> +  for (let i=0; i < genres.length; i++ ){
что-то очень много `for`. Используй методы массива

2021-08-17 08:59 UTC, DPGrachev commented on src/mock/film-card-mock.js
> +    while(arr.indexOf(value) >= 0){
Этот код был у меня в проекте первого JS, он подходил для решения задачи поэтому я его и вставил) На первом JS по этой  функции был точно такой же комментарий))

2021-08-17 10:04 UTC, merged